yekaswagger_home:
    path: /
    defaults: { _controller: YekaSwaggerBundle:Swagger:index }

yekaswagger_resources:
    path: /resources/{resourceName}
    defaults: { _controller: YekaSwaggerBundle:Swagger:resources, resourceName: ~ }
    requirements:
        resourceName: .*